import { emptyState, today, addMonths, type Access, type State } from "./model.js";
export const demoAccess: Access = {
  tenant: {
    id: "demo-centro",
    name: "Lubricentro Central",
    active: true,
    schemaVersion: 1,
    createdAt: new Date().toISOString(),
  },
  member: {
    uid: "demo-owner",
    tenantId: "demo-centro",
    role: "owner",
    active: true,
    name: "Xavier Guerrero",
    email: "admin@demo.local",
    customerId: null,
  },
};
const daysAgo = (days: number) =>
  new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
export function demoState(): State {
  const s = emptyState();
  const d = today();
  s.branches = [
    { id: "main", name: "Casa central", address: "Av. San Martín 1450" },
    { id: "north", name: "Sucursal Norte", address: "Av. Libertador 820" },
  ];
  s.customers = [
    {
      id: "c1",
      name: "Martín González",
      email: "martin@example.com",
      phone: "11 4567-8900",
      notes: "Prefiere turnos por la mañana.",
      pushEnabled: true,
    },
    {
      id: "c2",
      name: "Lucía Fernández",
      email: "lucia@example.com",
      phone: "11 5678-9012",
      notes: "",
      pushEnabled: true,
    },
    {
      id: "c3",
      name: "Diego Martínez",
      email: "diego@example.com",
      phone: "11 6789-0123",
      notes: "",
      pushEnabled: true,
    },
  ];
  s.vehicles = [
    {
      id: "v1",
      customerId: "c1",
      plate: "AE 345 FG",
      brand: "Volkswagen",
      model: "Golf 1.4 TSI",
      year: 2020,
      odometer: 78500,
      readingDate: daysAgo(3),
      previousOdometer: 74700,
      previousReadingDate: daysAgo(93),
      extinguisherDue: addMonths(d, 1),
    },
    {
      id: "v2",
      customerId: "c2",
      plate: "AF 789 CD",
      brand: "Toyota",
      model: "Corolla 2.0",
      year: 2022,
      odometer: 46200,
      readingDate: daysAgo(1),
      previousOdometer: null,
      previousReadingDate: "",
      extinguisherDue: daysAgo(-12),
    },
    {
      id: "v3",
      customerId: "c3",
      plate: "AC 123 HK",
      brand: "Ford",
      model: "Ranger 3.2",
      year: 2018,
      odometer: 128400,
      readingDate: d,
      previousOdometer: 119000,
      previousReadingDate: daysAgo(180),
      extinguisherDue: addMonths(d, 5),
    },
  ];
  s.products = [
    {
      id: "p1",
      name: "Shell Helix Ultra 5W-40",
      sku: "SH-5W40",
      unit: "litro",
      price: 14500,
      cost: 9800,
      stock: 84.5,
      minStock: 20,
      branchId: "main",
    },
    {
      id: "p2",
      name: "Filtro de aceite MANN W712/95",
      sku: "MN-W712",
      unit: "unidad",
      price: 18500,
      cost: 11000,
      stock: 4,
      minStock: 5,
      branchId: "main",
    },
    {
      id: "p3",
      name: "Mobil Super 3000 5W-30",
      sku: "MB-5W30",
      unit: "litro",
      price: 13200,
      cost: 8900,
      stock: 62,
      minStock: 20,
      branchId: "main",
    },
    {
      id: "p4",
      name: "Filtro de aire Toyota",
      sku: "TY-AIR",
      unit: "unidad",
      price: 22000,
      cost: 14500,
      stock: 12,
      minStock: 4,
      branchId: "main",
    },
  ];
  s.suppliers = [
    {
      id: "sup1",
      name: "Distribuidora del Automotor",
      email: "ventas@example.com",
      phone: "11 4000-1234",
    },
  ];
  s.services = [
    {
      id: "s1",
      name: "Cambio de aceite + filtro",
      labor: 18000,
      intervalKm: 10000,
      intervalMonths: 12,
      items: [
        { productId: "p1", quantity: 4.5 },
        { productId: "p2", quantity: 1 },
      ],
    },
    {
      id: "s2",
      name: "Cambio de filtro de aire",
      labor: 8000,
      intervalKm: 15000,
      intervalMonths: 12,
      items: [{ productId: "p4", quantity: 1 }],
    },
  ];
  s.appointments = [
    {
      id: "a1",
      customerId: "c1",
      vehicleId: "v1",
      branchId: "main",
      date: d,
      time: "09:00",
      reason: "Cambio de aceite + filtro",
      status: "confirmed",
      technician: "Nicolás",
    },
    {
      id: "a2",
      customerId: "c2",
      vehicleId: "v2",
      branchId: "main",
      date: d,
      time: "10:30",
      reason: "Control de niveles",
      status: "requested",
      technician: "",
    },
    {
      id: "a3",
      customerId: "c3",
      vehicleId: "v3",
      branchId: "main",
      date: d,
      time: "14:00",
      reason: "Service completo",
      status: "confirmed",
      technician: "Nicolás",
    },
  ];
  s.orders = [
    {
      serviceName: "Cambio de aceite + filtro",
      id: "ot1001",
      customerId: "c1",
      vehicleId: "v1",
      branchId: "main",
      serviceId: "s1",
      odometer: 78500,
      date: d,
      technician: "Nicolás",
      notes: "Revisar nivel de refrigerante.",
      checklist: ["Luces", "Niveles"],
      status: "working",
      items: [
        {
          productId: "p1",
          name: "Shell Helix Ultra 5W-40",
          quantity: 4.5,
          price: 14500,
          cost: 9800,
        },
        {
          productId: "p2",
          name: "Filtro de aceite MANN W712/95",
          quantity: 1,
          price: 18500,
          cost: 11000,
        },
      ],
      labor: 18000,
      intervalKm: 10000,
      intervalMonths: 12,
    },
    {
      serviceName: "Cambio de aceite + filtro",
      id: "ot1002",
      customerId: "c3",
      vehicleId: "v3",
      branchId: "main",
      serviceId: "s1",
      odometer: 128400,
      date: d,
      technician: "Nicolás",
      notes: "",
      checklist: [],
      status: "received",
      items: [
        {
          productId: "p1",
          name: "Shell Helix Ultra 5W-40",
          quantity: 4.5,
          price: 14500,
          cost: 9800,
        },
        {
          productId: "p2",
          name: "Filtro de aceite MANN W712/95",
          quantity: 1,
          price: 18500,
          cost: 11000,
        },
      ],
      labor: 18000,
      intervalKm: 10000,
      intervalMonths: 12,
    },
  ];
  s.reminders = [
    {
      id: "r1",
      customerId: "c1",
      vehicleId: "v1",
      title: "Cambio de aceite + filtro",
      dueDate: addMonths(d, 2),
      dueKm: 79000,
      status: "active",
      source: "s1",
    },
    {
      id: "r2",
      customerId: "c2",
      vehicleId: "v2",
      title: "Renovación de matafuegos",
      dueDate: daysAgo(-12),
      dueKm: null,
      status: "active",
      source: "extinguisher",
    },
  ];
  s.notifications = [
    {
      id: "n1",
      customerId: "c1",
      vehicleId: "v1",
      title: "Tu próximo cambio se acerca",
      body: "Según tu uso promedio, se acerca el próximo cambio de aceite. Actualizá el kilometraje o solicitá un turno.",
      date: new Date().toISOString(),
      read: false,
    },
  ];
  s.cash = [
    {
      id: "cash1",
      branchId: "main",
      openedAt: d + "T10:00:00.000Z",
      closedAt: null,
      opening: 50000,
      counted: null,
      expected: null,
      uid: "demo-owner",
    },
  ];
  s.sales = [
    {
      id: "sale1",
      customerId: null,
      branchId: "main",
      orderId: null,
      date: d + "T12:00:00.000Z",
      total: 58000,
      cost: 39200,
      method: "cash",
      items: [{ name: "Shell Helix Ultra 5W-40", quantity: 4, price: 14500 }],
    },
    {
      id: "sale2",
      customerId: null,
      branchId: "main",
      orderId: null,
      date: d + "T13:00:00.000Z",
      total: 22000,
      cost: 14500,
      method: "transfer",
      items: [{ name: "Filtro de aire Toyota", quantity: 1, price: 22000 }],
    },
  ];
  return s;
}
